### ISSUE TITLE
data.php needs help

### ISSUE THREAD

**Issue by CatalyticWeb** [CatalyticWeb/Chill-Appz-Startup#21]
data.php is either not receiving the POST from the previous page or not handling the values correctly. Another option may be that the JS is not adding the correct values to the hidden fields on angular.html

**Comment by barrycumbie** [comment]
> data.php is either not receiving the POST from the previous page or not handling the values correctly. Another option may be that the JS is not adding the correct values to the hidden fields on angular.html

@CatalyticWeb what is the previous page?

`whatpage.php` ==> 'data.php'

**Comment by barrycumbie** [comment]
# Current issue 

from:

https://chill-apps.herokuapp.com

click on stuff

hit `go`

and get this

```
Cannot POST /data.php
```

**Comment by CatalyticWeb** [comment]
Moved away from PHP. Focusing on utilizing Node with express and angular to manage data in motion.

Closing this issue.
